In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/raw/01_fund_master.csv")

df.head()

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
0,119551,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2006-02-14,NIFTY 100 TRI,1.54,1.0,500,1000,Sohini Andani,Moderate,EC01
1,119552,SBI Mutual Fund,SBI Bluechip Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.66,1.0,500,1000,Sohini Andani,Moderate,EC01
2,119598,SBI Mutual Fund,SBI Small Cap Fund - Regular Plan - Growth,Equity,Small Cap,Regular,2009-09-09,BSE 250 SmallCap TRI,1.43,1.0,500,1000,R. Srinivasan,Very High,EC03
3,119599,SBI Mutual Fund,SBI Small Cap Fund - Direct Plan - Growth,Equity,Small Cap,Direct,2013-01-01,BSE 250 SmallCap TRI,0.72,1.0,500,1000,R. Srinivasan,Very High,EC03
4,119120,SBI Mutual Fund,SBI Magnum Gilt Fund - Regular Plan - Growth,Debt,Gilt,Regular,2000-12-30,CRISIL Dynamic Gilt Index,0.77,0.0,500,1000,Dinesh Ahuja,Low,DC02

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   fund_house          40 non-null     str
 2   scheme_name         40 non-null     str
 3   category            40 non-null     str
 4   sub_category        40 non-null     str
 5   plan                40 non-null     str
 6   launch_date         40 non-null     str
 7   benchmark           40 non-null     str
 8   expense_ratio_pct   40 non-null     float64
 9   exit_load_pct       40 non-null     float64
 10  min_sip_amount      40 non-null     int64
 11  min_lumpsum_amount  40 non-null     int64
 12  fund_manager        40 non-null     str
 13  risk_category       40 non-null     str
 14  sebi_category_code  40 non-null     str
dtypes: float64(2), int64(3), str(10)
memory usage: 4.8 KB

In [4]:
df.isnull().sum()

amfi_code             0
fund_house            0
scheme_name           0
category              0
sub_category          0
plan                  0
launch_date           0
benchmark             0
expense_ratio_pct     0
exit_load_pct         0
min_sip_amount        0
min_lumpsum_amount    0
fund_manager          0
risk_category         0
sebi_category_code    0
dtype: int64

In [5]:
df.isnull().sum()

amfi_code             0
fund_house            0
scheme_name           0
category              0
sub_category          0
plan                  0
launch_date           0
benchmark             0
expense_ratio_pct     0
exit_load_pct         0
min_sip_amount        0
min_lumpsum_amount    0
fund_manager          0
risk_category         0
sebi_category_code    0
dtype: int64

In [6]:
df.dtypes

amfi_code               int64
fund_house                str
scheme_name               str
category                  str
sub_category              str
plan                      str
launch_date               str
benchmark                 str
expense_ratio_pct     float64
exit_load_pct         float64
min_sip_amount          int64
min_lumpsum_amount      int64
fund_manager              str
risk_category             str
sebi_category_code        str
dtype: object

In [7]:
df["launch_date"] = pd.to_datetime(df["launch_date"])

In [8]:
df.dtypes

amfi_code                      int64
fund_house                       str
scheme_name                      str
category                         str
sub_category                     str
plan                             str
launch_date           datetime64[us]
benchmark                        str
expense_ratio_pct            float64
exit_load_pct                float64
min_sip_amount                 int64
min_lumpsum_amount             int64
fund_manager                     str
risk_category                    str
sebi_category_code               str
dtype: object

In [9]:
df.isnull().sum()

amfi_code             0
fund_house            0
scheme_name           0
category              0
sub_category          0
plan                  0
launch_date           0
benchmark             0
expense_ratio_pct     0
exit_load_pct         0
min_sip_amount        0
min_lumpsum_amount    0
fund_manager          0
risk_category         0
sebi_category_code    0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.to_csv("../data/processed/01_fund_master_clean.csv", index=False)

In [12]:
df.isnull().sum()

amfi_code             0
fund_house            0
scheme_name           0
category              0
sub_category          0
plan                  0
launch_date           0
benchmark             0
expense_ratio_pct     0
exit_load_pct         0
min_sip_amount        0
min_lumpsum_amount    0
fund_manager          0
risk_category         0
sebi_category_code    0
dtype: int64

In [13]:
df.duplicated().sum()

np.int64(0)

In [14]:
df2 = pd.read_csv("../data/raw/02_nav_history.csv")
df2.head()

   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869
3     119551  2022-01-06  55.4550
4     119551  2022-01-07  55.3692

In [15]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 46000 entries, 0 to 45999
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   amfi_code  46000 non-null  int64
 1   date       46000 non-null  str
 2   nav        46000 non-null  float64
dtypes: float64(1), int64(1), str(1)
memory usage: 1.1 MB

In [16]:
df2.isnull().sum()

amfi_code    0
date         0
nav          0
dtype: int64

In [17]:
df2.duplicated().sum()

np.int64(0)

In [18]:
df2["date"] = pd.to_datetime(df2["date"])

df2.to_csv(
    "../data/processed/02_nav_history_clean.csv",
    index=False
)

print("Dataset 2 cleaned and saved!")

Dataset 2 cleaned and saved!

In [19]:
df2["date"] = pd.to_datetime(df2["date"])

df2.to_csv(
    "../data/processed/02_nav_history_clean.csv",
    index=False
)

print("Dataset 2 cleaned and saved!")

Dataset 2 cleaned and saved!

In [20]:
df3 = pd.read_csv("../data/raw/03_aum_by_fund_house.csv")

df3.info()

<class 'pandas.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            90 non-null     str
 1   fund_house      90 non-null     str
 2   aum_lakh_crore  90 non-null     float64
 3   aum_crore       90 non-null     int64
 4   num_schemes     90 non-null     int64
dtypes: float64(1), int64(2), str(2)
memory usage: 3.6 KB

In [21]:
df3.isnull().sum()

date              0
fund_house        0
aum_lakh_crore    0
aum_crore         0
num_schemes       0
dtype: int64

In [22]:
df3.duplicated().sum()

np.int64(0)

In [23]:
df3["date"] = pd.to_datetime(df3["date"])

df3.to_csv(
    "../data/processed/03_aum_by_fund_house_clean.csv",
    index=False
)

print("Dataset 3 cleaned and saved!")

Dataset 3 cleaned and saved!

In [24]:
df4 = pd.read_csv("../data/raw/04_monthly_sip_inflows.csv")

df4.info()

<class 'pandas.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 6 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   month                      48 non-null     str
 1   sip_inflow_crore           48 non-null     int64
 2   active_sip_accounts_crore  48 non-null     float64
 3   new_sip_accounts_lakh      48 non-null     float64
 4   sip_aum_lakh_crore         48 non-null     float64
 5   yoy_growth_pct             36 non-null     float64
dtypes: float64(4), int64(1), str(1)
memory usage: 2.4 KB

In [25]:
df4.duplicated().sum()

np.int64(0)

In [26]:
df4["month"] = pd.to_datetime(df4["month"])

df4.to_csv(
    "../data/processed/04_monthly_sip_inflows_clean.csv",
    index=False
)

print("Dataset 4 cleaned and saved!")

Dataset 4 cleaned and saved!

In [27]:
df5 = pd.read_csv("../data/raw/05_category_inflows.csv")

df5.info()

<class 'pandas.DataFrame'>
RangeIndex: 144 entries, 0 to 143
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   month             144 non-null    str
 1   category          144 non-null    str
 2   net_inflow_crore  144 non-null    float64
dtypes: float64(1), str(2)
memory usage: 3.5 KB

In [28]:
df5.isnull().sum()

month               0
category            0
net_inflow_crore    0
dtype: int64

In [29]:
df5.duplicated().sum()

np.int64(0)

In [30]:
df5["month"] = pd.to_datetime(df5["month"])

df5.to_csv(
    "../data/processed/05_category_inflows_clean.csv",
    index=False
)

print("Dataset 5 cleaned and saved!")

Dataset 5 cleaned and saved!

In [31]:
df6 = pd.read_csv("../data/raw/06_industry_folio_count.csv")

df6.info()

<class 'pandas.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   month                21 non-null     str
 1   total_folios_crore   21 non-null     float64
 2   equity_folios_crore  21 non-null     float64
 3   debt_folios_crore    21 non-null     float64
 4   hybrid_folios_crore  21 non-null     float64
 5   others_folios_crore  21 non-null     float64
dtypes: float64(5), str(1)
memory usage: 1.1 KB

In [32]:
df6.isnull().sum()

month                  0
total_folios_crore     0
equity_folios_crore    0
debt_folios_crore      0
hybrid_folios_crore    0
others_folios_crore    0
dtype: int64

In [33]:
df6.duplicated().sum()

np.int64(0)

In [34]:
df6["month"] = pd.to_datetime(df6["month"])

df6.to_csv(
    "../data/processed/06_industry_folio_count_clean.csv",
    index=False
)

print("Dataset 6 cleaned and saved!")

Dataset 6 cleaned and saved!

In [35]:
df7 = pd.read_csv("../data/raw/07_scheme_performance.csv")

df7.info()

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   scheme_name         40 non-null     str
 2   fund_house          40 non-null     str
 3   category            40 non-null     str
 4   plan                40 non-null     str
 5   return_1yr_pct      40 non-null     float64
 6   return_3yr_pct      40 non-null     float64
 7   return_5yr_pct      40 non-null     float64
 8   benchmark_3yr_pct   40 non-null     float64
 9   alpha               40 non-null     float64
 10  beta                40 non-null     float64
 11  sharpe_ratio        40 non-null     float64
 12  sortino_ratio       40 non-null     float64
 13  std_dev_ann_pct     40 non-null     float64
 14  max_drawdown_pct    40 non-null     float64
 15  aum_crore           40 non-null     int64
 16  expense_ratio_pct   40 non-null     float64
 17  morningstar_rating  40 non-null     int64
 18  risk_grade          40 non-null     str
dtypes: float64(11), int64(3), str(5)
memory usage: 6.1 KB

In [36]:
df7.isnull().sum()

amfi_code             0
scheme_name           0
fund_house            0
category              0
plan                  0
return_1yr_pct        0
return_3yr_pct        0
return_5yr_pct        0
benchmark_3yr_pct     0
alpha                 0
beta                  0
sharpe_ratio          0
sortino_ratio         0
std_dev_ann_pct       0
max_drawdown_pct      0
aum_crore             0
expense_ratio_pct     0
morningstar_rating    0
risk_grade            0
dtype: int64

In [37]:
df7.duplicated().sum()

np.int64(0)

In [38]:
df7.to_csv(
    "../data/processed/07_scheme_performance_clean.csv",
    index=False
)

print("Dataset 7 cleaned and saved!")

Dataset 7 cleaned and saved!

In [39]:
df8 = pd.read_csv("../data/raw/08_investor_transactions.csv")

df8.info()

<class 'pandas.DataFrame'>
RangeIndex: 32778 entries, 0 to 32777
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   investor_id         32778 non-null  str
 1   transaction_date    32778 non-null  str
 2   amfi_code           32778 non-null  int64
 3   transaction_type    32778 non-null  str
 4   amount_inr          32778 non-null  int64
 5   state               32778 non-null  str
 6   city                32778 non-null  str
 7   city_tier           32778 non-null  str
 8   age_group           32778 non-null  str
 9   gender              32778 non-null  str
 10  annual_income_lakh  32778 non-null  float64
 11  payment_mode        32778 non-null  str
 12  kyc_status          32778 non-null  str
dtypes: float64(1), int64(2), str(10)
memory usage: 3.3 MB

In [40]:
df8.isnull().sum()

investor_id           0
transaction_date      0
amfi_code             0
transaction_type      0
amount_inr            0
state                 0
city                  0
city_tier             0
age_group             0
gender                0
annual_income_lakh    0
payment_mode          0
kyc_status            0
dtype: int64

In [41]:
df8.duplicated().sum()

np.int64(0)

In [42]:
df8.to_csv(
    "../data/processed/08_investor_transactions_clean.csv",
    index=False
)

print("Dataset 8 cleaned and saved!")

Dataset 8 cleaned and saved!

In [43]:
df9 = pd.read_csv("../data/raw/09_portfolio_holdings.csv")

df9.info()

<class 'pandas.DataFrame'>
RangeIndex: 322 entries, 0 to 321
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   amfi_code          322 non-null    int64
 1   stock_symbol       322 non-null    str
 2   stock_name         322 non-null    str
 3   sector             322 non-null    str
 4   weight_pct         322 non-null    float64
 5   market_value_cr    322 non-null    float64
 6   current_price_inr  322 non-null    float64
 7   portfolio_date     322 non-null    str
dtypes: float64(3), int64(1), str(4)
memory usage: 20.3 KB

In [44]:
df9.isnull().sum()

amfi_code            0
stock_symbol         0
stock_name           0
sector               0
weight_pct           0
market_value_cr      0
current_price_inr    0
portfolio_date       0
dtype: int64

In [45]:
df9.duplicated().sum()

np.int64(0)

In [46]:
df9.to_csv(
    "../data/processed/09_portfolio_holdings_clean.csv",
    index=False
)

print("Dataset 9 cleaned and saved!")

Dataset 9 cleaned and saved!

In [47]:
df10 = pd.read_csv("../data/raw/10_benchmark_indices.csv")

df10.info()

<class 'pandas.DataFrame'>
RangeIndex: 8050 entries, 0 to 8049
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         8050 non-null   str
 1   index_name   8050 non-null   str
 2   close_value  8050 non-null   float64
dtypes: float64(1), str(2)
memory usage: 188.8 KB

In [48]:
df10.isnull().sum()

date           0
index_name     0
close_value    0
dtype: int64

In [49]:
df10.duplicated().sum()

np.int64(0)

In [50]:
df10["date"] = pd.to_datetime(df10["date"])

df10.to_csv(
    "../data/processed/10_benchmark_indices_clean.csv",
    index=False
)

print("Dataset 10 cleaned and saved!")

Dataset 10 cleaned and saved!